[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lock = "84s5XRQZycmBMmj3jCsJ9T5C5znKQCfuVchNsnmo3uqk"
spltoken = "6siE68rhixWS5EMgfNTNjMGmv1MoqC2G9zMbJ7CA5t4R"
spltokencpi = "MVyr524TCDeXQSkmaZDFJertE3y1Ua4o9KnEZQCosna"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zero/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
