[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spltoken = "9q76qB4ieWmZzQ3tbgqtKNtLScBj4QD3w5942GEBsjqz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zero/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
