[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
helloworld = "3dcedJWgjG8aDroaVHJK4AYv9Aa1B9mVBx8VLhN66CgP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/zero/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
