[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
helloworld = "8rXyiVRE32hi9d8PTxjNavGo2doakmBpvry82AXZrsVd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/zero/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
