[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
helloworld = "DTuUrdBSiTh4ven5y4QYhYWLBzb6ehjZbKhLsBNKPkps"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/zero/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
