[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_anchor_demo = "tdeCmVc559AJhzH93DTrBRms3H3i9KNdc7Ef4AtMMkD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zero/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
